### ISSUE TITLE
Missing orthophoto's

### ISSUE THREAD

**Issue by posikifi** [nls-oskari/oskari-server#11]
Hi,

I tried to add NLS's orthophotos to my Oskari-server. Seems to be ok, but not showed in Oskari frontend. As you see images are downloaded, but not loaded in Oskari.

![oskari_server_missing_orthophotos](https://f.cloud.github.com/assets/1785962/2383363/4a464e1a-a8fb-11e3-8be0-c04a52d174bf.png)

**Comment by ZakarFin** [comment]
The whole WMTS-layer handling has been rewitten after this and this has been fixed a while ago (old issue).
