### ISSUE TITLE
Geoserver layer definition

### ISSUE THREAD

**Issue by posikifi** [nls-oskari/oskari-server#16]
Hi,

Geoserver installation documentation [Enabling My Places With Postgis] (https://github.com/nls-oskari/oskari-server/blob/master/docs/EnablingMyPlacesWithPostgis.md#enabling-my-places-with-postgis) lacks information: 
* I presume coordinate boundinx boxes should be spefiy also for my_places_categories.
* Tile service: should this follow EPSG:3067 coordinate system and JHS180 tile grid, those details could be also here
* Structure of the documentation is quite bad. I suggest that this "copy-this-data-dir-to-your-geoserver", will be removed. No sense to copy all those sample datasets etc.

P

**Comment by ZakarFin** [comment]
I think we finally have a better way of doing this. Basically you configure the geoserver url and credentials to oskari-ext.properties and the setup-webapp can be used to generate the Geoserver configuration (uses Geoserver REST API). This also allows you to select the native coordinate system for Oskari user content (myplaces/analysis/userlayers).

It's documented here http://www.oskari.org/documentation/backend/setup-geoserver (propably could be a more elaborate with the Geoserver settings that are used). Some of the old documentation in oskari.org still need updating and there's seems to be some issues with Geoserver handling the REST API differently with different versions. Anyway this works with the Geoserver shipped with the Oskari Jetty distribution package that you can download from http://oskari.org/download. Currently it uses 2.7.1.1 and also has a pregenerated data dir so you can check the settings and manually configure another geoserver the same way.
